#!/bin/bash
# Phase 1.5: Backup Configuration Script
# Sets up automated database backups

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Load configuration
if [ -f .env.pi ]; then
    source .env.pi
else
    echo -e "${RED}Error: .env.pi file not found${NC}"
    exit 1
fi

echo -e "${GREEN}=== Phase 1.5: Backup Configuration ===${NC}"
echo "Target: $PI_USER@$PI_HOST"
echo ""

# Function to run commands on Pi
run_on_pi() {
    sshpass -p "$PI_PASSWORD" ssh -o StrictHostKeyChecking=no "$PI_USER@$PI_HOST" "$1"
}

# Task 1.5.1: Create Backup Script
echo -e "${YELLOW}[1.5.1] Creating backup script on Raspberry Pi...${NC}"

# Create backup directory
echo "Creating backup directory: $BACKUP_DIR"
run_on_pi "mkdir -p $BACKUP_DIR"

# Create the backup script
echo "Creating backup script..."
run_on_pi "cat > ~/backup_db.sh << 'BACKUP_SCRIPT'
#!/bin/bash
# Automated Database Backup Script
# Generated by Phase 1 setup

BACKUP_DIR=\"$BACKUP_DIR\"
DB_NAME=\"$DB_NAME\"
DB_USER=\"$DB_USER\"
DB_PASSWORD=\"$DB_PASSWORD\"
RETENTION_DAYS=$BACKUP_RETENTION_DAYS
TIMESTAMP=\$(date +%Y%m%d_%H%M%S)
BACKUP_FILE=\"\${BACKUP_DIR}/\${DB_NAME}_\${TIMESTAMP}.sql\"

# Create backup
echo \"Starting backup: \$BACKUP_FILE\"
mysqldump -u \"\$DB_USER\" -p\"\$DB_PASSWORD\" \"\$DB_NAME\" > \"\$BACKUP_FILE\" 2>/dev/null

# Compress backup
gzip \"\$BACKUP_FILE\"
echo \"Backup completed: \${BACKUP_FILE}.gz\"

# Get backup size
SIZE=\$(du -h \"\${BACKUP_FILE}.gz\" | cut -f1)
echo \"Backup size: \$SIZE\"

# Clean up old backups
echo \"Cleaning up backups older than \$RETENTION_DAYS days...\"
find \"\$BACKUP_DIR\" -name \"\${DB_NAME}_*.sql.gz\" -mtime +\$RETENTION_DAYS -delete
echo \"Cleanup complete\"

# List recent backups
echo \"Recent backups:\"
ls -lh \"\$BACKUP_DIR\" | tail -5
BACKUP_SCRIPT"

# Make script executable
run_on_pi "chmod +x ~/backup_db.sh"

# Test the backup script
echo "Testing backup script..."
run_on_pi "~/backup_db.sh"

echo -e "${GREEN}✓ Backup script created and tested${NC}"
echo ""

# Task 1.5.2: Set Up Automated Backups
echo -e "${YELLOW}[1.5.2] Setting up automated backups with cron...${NC}"

# Check if cron job already exists
EXISTING_CRON=$(run_on_pi "crontab -l 2>/dev/null | grep 'backup_db.sh' || echo ''")

if [ -n "$EXISTING_CRON" ]; then
    echo "Backup cron job already exists:"
    echo "$EXISTING_CRON"
else
    echo "Adding cron job for daily backups at 2:00 AM..."
    
    # Add cron job (daily at 2 AM)
    run_on_pi "(crontab -l 2>/dev/null || echo ''; echo '# Motorbike Parking App Database Backup'; echo '0 2 * * * /home/$PI_USER/backup_db.sh >> /home/$PI_USER/backup.log 2>&1') | crontab -"
    
    echo "Cron job added successfully"
fi

# Display current crontab
echo ""
echo "Current cron jobs:"
run_on_pi "crontab -l | grep -A1 'Motorbike' || echo 'No cron jobs found'"

echo -e "${GREEN}✓ Automated backups configured${NC}"
echo ""

echo -e "${GREEN}=== Phase 1.5 Complete ===${NC}"
echo ""
echo -e "${YELLOW}Backup Configuration Summary:${NC}"
echo "  Backup Directory: $BACKUP_DIR"
echo "  Backup Schedule: Daily at 2:00 AM"
echo "  Retention Period: $BACKUP_RETENTION_DAYS days"
echo "  Manual Backup: ssh $PI_USER@$PI_HOST '~/backup_db.sh'"
echo ""
echo -e "${YELLOW}Backup Files Location:${NC}"
run_on_pi "ls -lh $BACKUP_DIR 2>/dev/null | tail -5 || echo 'No backups yet'"
echo ""
echo -e "${GREEN}🎉 PHASE 1 COMPLETE! 🎉${NC}"
echo ""
echo -e "${YELLOW}Summary of Phase 1:${NC}"
echo "  ✓ Raspberry Pi OS updated"
echo "  ✓ MariaDB 10.11.14 installed and running"
echo "  ✓ Database '$DB_NAME' created"
echo "  ✓ User '$DB_USER' created with privileges"
echo "  ✓ Schema imported (4 tables, 2 views, 2 triggers, 2 procedures)"
echo "  ✓ Triggers and stored procedures tested"
echo "  ✓ Remote access configured"
echo "  ✓ Automated backups set up"
echo ""
echo -e "${YELLOW}Database Connection Details:${NC}"
echo "  Host: $DB_HOST"
echo "  Port: $DB_PORT"
echo "  Database: $DB_NAME"
echo "  User: $DB_USER"
echo "  Password: $DB_PASSWORD"
echo ""
echo -e "${YELLOW}Next Phase:${NC}"
echo "  Phase 2: Backend API Development"
echo "  See: MIGRATION_TODO_LIST.md"
